"""Diagnostic test for planner integration.

Tests all three conditions side-by-side on the same problem:
1. OVERALL_AND_INDIVIDUAL (fixed budgets with consequence framing)
2. PLANNER_ESTIMATED (dynamic budgets from planner)

Shows the actual prompts generated for each condition.
"""

import asyncio
from datasets import load_dataset
from dotenv import load_dotenv

from agent_budget.core import MultiAgentAwarenessCondition, get_coder_budget
from agent_budget.code_review_prompts import (
    generate_budget_message,
)
from agent_budget.planner import estimate_budget


async def compare_conditions_on_problem(problem: dict, difficulty: str = "medium"):
    """Compare prompts generated by different conditions for the same problem."""
    title = problem.get("question_title", "Unknown")
    description = problem.get("question_content", "")

    print("=" * 70)
    print(f"PROBLEM: {title}")
    print(f"DIFFICULTY: {difficulty}")
    print("=" * 70)

    # Fixed budget for this difficulty
    fixed_budget = get_coder_budget(difficulty).total

    # Get planner estimate
    print("\n--- PLANNER ESTIMATE ---")
    estimate = await estimate_budget(description)
    print(f"Estimated tokens: {estimate.estimated_tokens_per_iteration}")
    print(f"Estimated iterations: {estimate.estimated_iterations}")
    print(f"Reasoning: {estimate.reasoning}")

    # Compare to fixed budget
    diff = estimate.estimated_tokens_per_iteration - fixed_budget
    diff_pct = (diff / fixed_budget) * 100
    print(f"\nFixed budget for {difficulty}: {fixed_budget}")
    print(
        f"Planner estimate: {estimate.estimated_tokens_per_iteration} ({diff:+d}, {diff_pct:+.1f}%)"
    )

    # Generate messages for each condition
    conditions = [
        (MultiAgentAwarenessCondition.OVERALL_AND_INDIVIDUAL, "Fixed Budget"),
        (MultiAgentAwarenessCondition.PLANNER_ESTIMATED, "Planner Estimated"),
    ]

    for condition, label in conditions:
        print(f"\n--- {label.upper()} CONDITION ---")

        planner_dict = (
            estimate.to_dict()
            if condition == MultiAgentAwarenessCondition.PLANNER_ESTIMATED
            else None
        )

        message = generate_budget_message(
            awareness_condition=condition,
            max_iterations=3,
            agent_role="Coder",
            difficulty=difficulty,
            planner_estimate=planner_dict,
        )

        print(f"Budget message:\n{message}")


async def run_diagnostic():
    """Run diagnostic comparing conditions on real problems."""
    load_dotenv()

    # Load one problem of each difficulty
    dataset = load_dataset(
        "livecodebench/code_generation_lite",
        split="test",
        version_tag="release_v6",
        trust_remote_code=True,
    )

    easy_problem = next(p for p in dataset if p.get("difficulty") == "easy")
    medium_problem = next(p for p in dataset if p.get("difficulty") == "medium")

    print("\n" + "=" * 70)
    print("DIAGNOSTIC: COMPARING BUDGET CONDITIONS")
    print("=" * 70)

    await compare_conditions_on_problem(easy_problem, "easy")
    print("\n" * 2)
    await compare_conditions_on_problem(medium_problem, "medium")

    # Test that PLANNER_ESTIMATED produces varied estimates
    print("\n" + "=" * 70)
    print("VARIANCE CHECK: Do planner estimates vary across problems?")
    print("=" * 70)

    # Get estimates for 5 problems
    problems = list(dataset)[:5]
    estimates = []

    for p in problems:
        est = await estimate_budget(p.get("question_content", ""))
        estimates.append(
            {
                "title": p.get("question_title", "")[:30],
                "difficulty": p.get("difficulty", ""),
                "tokens": est.estimated_tokens_per_iteration,
                "iterations": est.estimated_iterations,
            }
        )

    print("\nEstimates for 5 problems:")
    for e in estimates:
        print(
            f"  {e['difficulty']:8} | {e['tokens']:5} tok | {e['iterations']} iter | {e['title']}"
        )

    unique_tokens = len(set(e["tokens"] for e in estimates))
    print(f"\nUnique token values: {unique_tokens}/5")
    print(f"Variance exists: {'Yes' if unique_tokens > 1 else 'No (all same!)'}")


if __name__ == "__main__":
    asyncio.run(run_diagnostic())
